# Step 1: Use Nginx as the base image
FROM nginx:alpine

# Step 2: Copy the dist folder generated by Angular build into Nginx’s HTML folder
COPY ./dist/sakai-ng /usr/share/nginx/html

# Step 3: Copy the custom nginx.conf file into the container
COPY nginx.conf /etc/nginx/nginx.conf

# Step 4: Expose the port that Nginx is listening on (default 80)
EXPOSE 80

# Step 5: Run Nginx in the foreground
CMD ["nginx", "-g", "daemon off;"]
