apiVersion: v1
kind: Service
metadata:
  name: hackathonnet-frontend-service
  namespace: hackathonnet
spec:
  selector:
    app: hackathonnet-frontend
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80          # Port inside the cluster
      targetPort: 80    # Container port