apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: hackathonnet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.4
          env:
            - name: MYSQL_ALLOW_EMPTY_PASSWORD
              value: "yes"
            - name: MYSQL_DATABASE
              value: "pi111"
          ports:
            - containerPort: 3306